version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: dockerfiles/dockerfile.web 
    container_name: php-web
    restart: always
    depends_on:
      - db
    ports:
      - "80:80"
    networks:
      - app-network
    environment:
      DB_HOST: ${DB_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
