FROM php:7.4-apache

# Install mysqli
RUN docker-php-ext-install mysqli

# Install additional dependencies
RUN apt-get update && apt-get install -y \
    libpng-dev \
    git \
    libjpeg-dev \
    libfreetype6-dev \
    libwebp-dev && \
    docker-php-ext-configure gd --with-freetype --with-jpeg --with-webp && \
    docker-php-ext-install gd


# Clean up
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

RUN git clone https://github.com/Kapysto4ka/php-mysql-crud /var/www/html

EXPOSE ${APACHE_PORT}
